services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: mern_mini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_DB: mern_mini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      PORT: 8081
    ports:
      - "3000:3000"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    command: tail -f /dev/null
