services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/mern-mini
      PORT: 8081
    ports:
      - "3000:3000"
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    command: tail -f /dev/null
